<<<<<<< HEAD
runtime: nodejs
env: flex
env_variables:
  DB_NAME: "DBBanHang_old"
  DB_USER: "root"
  DB_PASSWORD: "12345678"
  INSTANCE_CONNECTION_NAME: "db-nmptudw19:asia-southeast1:dbbanhang"
beta_settings:
  cloud_sql_instances: "db-nmptudw19:asia-southeast1:dbbanhang"
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
=======
DB_DATABASE= DBBanHang
DB_USERNAME= root
DB_PASSWORD= 123456
DB_HOST= localhost
>>>>>>> cfc027366857301bf9ecb755c7a564a2b5bb5f6f
